"""Build full_v6 and its empennage parametric variants, and run VSPAERO on them.

full_v6 vs full_v5
------------------
1. FUSELAGE: adopts the user's 2026-08-06 GUI reloft verbatim (7 stations, nose
   tip z=-1.93, nose blend to x=10.85, blunt capped radome) with ONE fix -- the
   tail terminated on a 1.667 ft circle with `CapUMaxOption = 0`, i.e. the body
   was left open: a 2.18 ft^2 hole at x=42.2. Here the tip is drawn down to
   0.60 ft and given a round end cap, recovering ~1.9 ft^2 of base area.
   The dead `Fuselage old` geom carried in the v5 file is dropped.
2. EMPENNAGE: areas are now parameters. v5's tails were sized against the
   pre-CG-fix wing position and never re-sized after the wing moved 3.1 ft
   forward, leaving c_HT = 1.34 / c_VT = 0.1225 at the true arms (size_tails.py).
3. Everything else -- wing, winglet, nacelle, pylon, belly fairing, dorsal fin --
   is carried over unchanged so the comparison isolates the empennage.

Experimental design: for the NP parametric ONLY S_HT moves (S_VT, wing position
and Xcg held), so dNP/dS_HT is clean. For the Cn_beta parametric only S_VT
moves. The coupled wing/CG solve then happens in size_tails.py, and the final
configuration is rebuilt and re-verified.

Usage (from this directory):
    python gen_v6.py --baseline            # build+run the v5-area reference
    python gen_v6.py --ht-sweep            # S_HT parametric, alpha sweeps
    python gen_v6.py --vt-sweep            # S_VT parametric, beta sweeps
    python gen_v6.py --final S_HT S_VT XW  # final config, alpha + beta
"""
import argparse
import math
import os
import subprocess

import size_tails as st

HERE = os.path.dirname(os.path.abspath(__file__))
VSPSCRIPT = os.path.join(HERE, "..", "..", "..",
                         "OpenVSP-3.51.2-win64-Python3.13",
                         "OpenVSP-3.51.2-win64", "vspscript.exe")
AIRFOIL = "../../../../airfoils/dat_clean/sc20412_selig.dat"

SREF, BREF, CREF = 193.678, 41.5324, 5.0236

# The user's fuselage, read straight out of full_v5.vsp3 (2026-08-06 GUI edit).
# x, z (ft), section type, height, width, top/bottom/side tangent angles (deg),
# tangent strength. Station 6's diameter is overridden below.
FUSE_L = 42.2
FUSE = [
    # x       z        H        W        top      bot       side     str  tbsym
    (0.000, -1.9285, 1.18617, 1.15014, 28.42105, 30.78947, 56.84211, 0.75, 0),
    (5.737, -1.1149, 3.70512, 4.88275, 28.42105, 0.00000, 7.10526, 1.00, 0),
    (10.852, 0.0000, 6.04571, 5.70454, -4.73684, -4.73684, 4.73684, 1.00, 1),
    (17.000, 0.0000, 6.10000, 6.10000, 0.00000, 0.00000, 0.00000, 1.00, 1),
    (23.400, 0.0000, 6.10000, 6.10000, 0.00000, 0.00000, 0.00000, 1.00, 1),
    (30.500, 0.4769, 4.69600, 4.69600, 0.00000, 0.00000, 0.00000, 1.00, 1),
    (42.200, 1.7956, 0.60000, 0.60000, 2.36842, -11.84211, -45.00000, 0.75, 0),
]

TEMPLATE = r'''// AUTO-GENERATED by gen_v6.py -- variant {name}
// S_HT = {s_ht:.4f} ft^2, S_VT = {s_vt:.4f} ft^2, wing root LE = {x_wing:.4f} ft
void main()
{{
    double wing_dx = {wing_dx:.4f};

    //================= Fuselage (user's v5 reloft, tail closed) ==============//
    string fid = AddGeom( "FUSELAGE", "" );
    SetGeomName( fid, "Fuselage" );
    SetParmVal( fid, "Length", "Design", {fuse_l} );
    Update();
    string fsurf = GetXSecSurf( fid, 0 );
    // 7 sections: the sparse-loft convention (config.md D.5d) -- one XSec per
    // curvature event, spline fairs between. Section 0 is a blunt radome ellipse
    // closed by a round cap, not a point.
    while ( GetNumXSec( fsurf ) > {nx} ) {{ CutXSec( fid, 1 ); }}
    while ( GetNumXSec( fsurf ) < {nx} ) {{ InsertXSec( fid, 1, XS_ELLIPSE ); }}
    Update();
    for ( int i = 0; i < {nx}; i++ ) {{ ChangeXSecShape( fsurf, i, XS_ELLIPSE ); }}
    Update();

    array<double> fx = {{ {fx} }};
    array<double> fz = {{ {fz} }};
    array<double> fh = {{ {fh} }};
    array<double> fw = {{ {fw} }};
    array<double> fta = {{ {fta} }};
    array<double> fba = {{ {fba} }};
    array<double> fsa = {{ {fsa} }};
    array<double> fst = {{ {fst} }};

    // XLocPercent is limit-clamped against neighbours, so a single assignment
    // pass silently loses stations -- alternate the direction until converged
    // (README gotcha 3).
    for ( int pass = 0; pass < 4; pass++ )
    {{
        for ( int k = 0; k < {nx}; k++ )
        {{
            int i = k;
            if ( pass % 2 == 0 ) {{ i = {nx} - 1 - k; }}
            SetParmVal( fid, "XLocPercent", "XSec_" + i, fx[i] / {fuse_l} );
            SetParmVal( fid, "ZLocPercent", "XSec_" + i, fz[i] / {fuse_l} );
            Update();
        }}
    }}
    for ( int i = 0; i < {nx}; i++ )
    {{
        SetParmVal( fid, "Ellipse_Height", "XSecCurve_" + i, fh[i] );
        SetParmVal( fid, "Ellipse_Width",  "XSecCurve_" + i, fw[i] );
        SetParmVal( fid, "TopLAngleSet",     "XSec_" + i, 1 );
        SetParmVal( fid, "TopLStrengthSet",  "XSec_" + i, 1 );
        SetParmVal( fid, "BottomLAngleSet",  "XSec_" + i, 1 );
        SetParmVal( fid, "BottomLStrengthSet", "XSec_" + i, 1 );
        SetParmVal( fid, "TopLAngle",      "XSec_" + i, fta[i] );
        SetParmVal( fid, "BottomLAngle",   "XSec_" + i, fba[i] );
        SetParmVal( fid, "LeftLAngle",     "XSec_" + i, fsa[i] );
        SetParmVal( fid, "RightLAngle",    "XSec_" + i, fsa[i] );
        SetParmVal( fid, "TopLStrength",    "XSec_" + i, fst[i] );
        SetParmVal( fid, "BottomLStrength", "XSec_" + i, fst[i] );
        SetParmVal( fid, "LeftLStrength",   "XSec_" + i, fst[i] );
        SetParmVal( fid, "RightLStrength",  "XSec_" + i, fst[i] );
        Update();
    }}
    // Nose: round cap (radome). Tail: round cap -- v5 left CapUMaxOption = 0,
    // i.e. an OPEN body with a 2.18 ft^2 hole at the tail. This is the fix.
    SetParmVal( fid, "CapUMinOption", "EndCap", 2 );
    SetParmVal( fid, "CapUMinLength", "EndCap", 1.0 );
    SetParmVal( fid, "CapUMinStrength", "EndCap", 1.0 );
    SetParmVal( fid, "CapUMaxOption", "EndCap", 2 );
    SetParmVal( fid, "CapUMaxLength", "EndCap", 0.5 );
    SetParmVal( fid, "CapUMaxStrength", "EndCap", 0.5 );
    SetParmVal( fid, "Tess_U", "Shape", 61 );
    SetParmVal( fid, "Tess_W", "Shape", 33 );
    Update();

    //======================= Belly fairing (unchanged) =======================//
    string bid = AddGeom( "FUSELAGE", "" );
    SetGeomName( bid, "BellyFairing" );
    SetParmVal( bid, "Length", "Design", 14.5 );
    SetParmVal( bid, "X_Rel_Location", "XForm", 16.0 + wing_dx );
    SetParmVal( bid, "Z_Rel_Location", "XForm", -2.20 );
    Update();
    string bsurf = GetXSecSurf( bid, 0 );
    for ( int i = 1; i <= 3; i++ ) {{ ChangeXSecShape( bsurf, i, XS_ROUNDED_RECTANGLE ); }}
    Update();
    array<double> bx = {{ 0.0,  3.0,  7.25, 11.5, 14.5 }};
    array<double> bw = {{ 0.00, 5.20, 7.00, 5.80, 0.00 }};
    array<double> bh = {{ 0.00, 2.40, 3.20, 2.75, 0.00 }};
    array<double> br = {{ 0.00, 1.08, 1.44, 1.24, 0.00 }};
    array<double> bz = {{ 0.25, 0.05, 0.00, 0.28, 1.05 }};
    for ( int pass = 0; pass < 4; pass++ )
    {{
        for ( int k = 0; k <= 4; k++ )
        {{
            int i = k;
            if ( pass % 2 == 0 ) {{ i = 4 - k; }}
            SetParmVal( bid, "XLocPercent", "XSec_" + i, bx[i] / 14.5 );
            SetParmVal( bid, "ZLocPercent", "XSec_" + i, bz[i] / 14.5 );
            Update();
        }}
    }}
    for ( int i = 1; i <= 3; i++ )
    {{
        SetParmVal( bid, "RoundedRect_Width",    "XSecCurve_" + i, bw[i] );
        SetParmVal( bid, "RoundedRect_Height",   "XSecCurve_" + i, bh[i] );
        SetParmVal( bid, "RoundRectXSec_Radius", "XSecCurve_" + i, br[i] );
    }}
    SetParmVal( bid, "Tess_U", "Shape", 25 );
    SetParmVal( bid, "Tess_W", "Shape", 37 );
    Update();

    //==================== Main wing + winglet (unchanged) ====================//
    string wid = AddGeom( "WING", "" );
    SetGeomName( wid, "MainWing" );
    SetParmVal( wid, "X_Rel_Location", "XForm", 19.0 + wing_dx );
    SetParmVal( wid, "Z_Rel_Location", "XForm", -2.6 );
    SetDriverGroup( wid, 1, SPAN_WSECT_DRIVER, ROOTC_WSECT_DRIVER, TIPC_WSECT_DRIVER );
    SetParmVal( wid, "Span", "XSec_1", 20.7662 );
    SetParmVal( wid, "Root_Chord", "XSec_1", 6.9086 );
    SetParmVal( wid, "Tip_Chord", "XSec_1", 2.4180 );
    SetParmVal( wid, "Sweep", "XSec_1", 13.8 );
    SetParmVal( wid, "Sweep_Location", "XSec_1", 0.25 );
    SetParmVal( wid, "Dihedral", "XSec_1", 3.0 );
    SetParmVal( wid, "Twist", "XSec_1", -3.0 );
    SetParmVal( wid, "Twist_Location", "XSec_1", 0.25 );
    SetParmVal( wid, "SectTess_U", "XSec_1", 30 );
    SetParmVal( wid, "Tess_W", "Shape", 41 );
    Update();
    InsertXSec( wid, 1, XS_FILE_AIRFOIL );
    SetDriverGroup( wid, 2, SPAN_WSECT_DRIVER, ROOTC_WSECT_DRIVER, TIPC_WSECT_DRIVER );
    SetParmVal( wid, "Span", "XSec_2", 2.40 );
    SetParmVal( wid, "Sweep", "XSec_2", 31.0 );
    SetParmVal( wid, "Sweep_Location", "XSec_2", 0.25 );
    SetParmVal( wid, "Dihedral", "XSec_2", 70.0 );
    SetParmVal( wid, "Twist", "XSec_2", -5.0 );
    SetParmVal( wid, "Twist_Location", "XSec_2", 0.25 );
    SetParmVal( wid, "SectTess_U", "XSec_2", 14 );
    Update();
    SetParmVal( wid, "Tip_Chord", "XSec_1", 2.4180 );
    Update();
    SetParmVal( wid, "Tip_Chord", "XSec_2", 0.95 );
    Update();
    string af_file = "{airfoil}";
    string wsurf = GetXSecSurf( wid, 0 );
    for ( int i = 0; i <= 2; i++ )
    {{
        ChangeXSecShape( wsurf, i, XS_FILE_AIRFOIL );
        ReadFileAirfoil( GetXSec( wsurf, i ), af_file );
    }}
    Update();

    //========================= Nacelles (unchanged) ==========================//
    string nid = AddGeom( "FUSELAGE", "" );
    SetGeomName( nid, "Nacelle" );
    SetParmVal( nid, "Length", "Design", 7.5 );
    SetParmVal( nid, "X_Rel_Location", "XForm", 25.1 + wing_dx );
    SetParmVal( nid, "Y_Rel_Location", "XForm", 6.9 );
    SetParmVal( nid, "Z_Rel_Location", "XForm", 1.0 );
    SetParmVal( nid, "Sym_Planar_Flag", "Sym", SYM_XZ );
    Update();
    string nsurf = GetXSecSurf( nid, 0 );
    for ( int i = 1; i <= 3; i++ ) {{ ChangeXSecShape( nsurf, i, XS_ELLIPSE ); }}
    Update();
    array<double> nx = {{ 0.0, 0.7, 2.8, 5.6, 7.5 }};
    array<double> nd = {{ 0.0, 2.1, 2.9, 2.6, 0.0 }};
    for ( int pass = 0; pass < 4; pass++ )
    {{
        for ( int k = 0; k <= 4; k++ )
        {{
            int i = k;
            if ( pass % 2 == 0 ) {{ i = 4 - k; }}
            SetParmVal( nid, "XLocPercent", "XSec_" + i, nx[i] / 7.5 );
            Update();
        }}
    }}
    for ( int i = 1; i <= 3; i++ )
    {{
        SetParmVal( nid, "Ellipse_Width",  "XSecCurve_" + i, nd[i] );
        SetParmVal( nid, "Ellipse_Height", "XSecCurve_" + i, nd[i] );
    }}
    SetParmVal( nid, "Tess_U", "Shape", 17 );
    SetParmVal( nid, "Tess_W", "Shape", 21 );
    Update();

    //========================== Pylons (unchanged) ===========================//
    string pid = AddGeom( "WING", "" );
    SetGeomName( pid, "Pylon" );
    SetParmVal( pid, "X_Rel_Location", "XForm", 24.0 + wing_dx );
    SetParmVal( pid, "Y_Rel_Location", "XForm", 6.9 );
    SetParmVal( pid, "Z_Rel_Location", "XForm", -2.0 );
    SetParmVal( pid, "X_Rel_Rotation", "XForm", 90.0 );
    SetParmVal( pid, "Sym_Planar_Flag", "Sym", SYM_XZ );
    SetDriverGroup( pid, 1, SPAN_WSECT_DRIVER, ROOTC_WSECT_DRIVER, TIPC_WSECT_DRIVER );
    SetParmVal( pid, "Span", "XSec_1", 3.2 );
    SetParmVal( pid, "Root_Chord", "XSec_1", 3.6 );
    SetParmVal( pid, "Tip_Chord", "XSec_1", 2.4 );
    SetParmVal( pid, "Sweep", "XSec_1", 35.0 );
    SetParmVal( pid, "Sweep_Location", "XSec_1", 0.0 );
    SetParmVal( pid, "Dihedral", "XSec_1", 0.0 );
    SetParmVal( pid, "Twist", "XSec_1", 0.0 );
    SetParmVal( pid, "SectTess_U", "XSec_1", 8 );
    Update();
    SetParmVal( pid, "ThickChord", "XSecCurve_0", 0.09 );
    SetParmVal( pid, "ThickChord", "XSecCurve_1", 0.09 );
    Update();

    //=================== Vertical tail (RESIZED, parametric) =================//
    string vid = AddGeom( "WING", "" );
    SetGeomName( vid, "VertTail" );
    SetParmVal( vid, "X_Rel_Location", "XForm", {x_vt:.4f} );
    SetParmVal( vid, "Z_Rel_Location", "XForm", 2.0 );
    SetParmVal( vid, "X_Rel_Rotation", "XForm", 90.0 );
    SetParmVal( vid, "Sym_Planar_Flag", "Sym", 0 );
    SetDriverGroup( vid, 1, SPAN_WSECT_DRIVER, ROOTC_WSECT_DRIVER, TIPC_WSECT_DRIVER );
    SetParmVal( vid, "Span", "XSec_1", {vt_b:.4f} );
    SetParmVal( vid, "Root_Chord", "XSec_1", {vt_cr:.4f} );
    SetParmVal( vid, "Tip_Chord", "XSec_1", {vt_ct:.4f} );
    SetParmVal( vid, "Sweep", "XSec_1", 35.0 );
    SetParmVal( vid, "Sweep_Location", "XSec_1", 0.25 );
    SetParmVal( vid, "Dihedral", "XSec_1", 0.0 );
    SetParmVal( vid, "Twist", "XSec_1", 0.0 );
    SetParmVal( vid, "SectTess_U", "XSec_1", 12 );
    Update();

    //======================== Dorsal fin (unchanged) =========================//
    string did = AddGeom( "WING", "" );
    SetGeomName( did, "DorsalFin" );
    SetParmVal( did, "X_Rel_Location", "XForm", 26.5 );
    SetParmVal( did, "Z_Rel_Location", "XForm", 2.60 );
    SetParmVal( did, "X_Rel_Rotation", "XForm", 90.0 );
    SetParmVal( did, "Sym_Planar_Flag", "Sym", 0 );
    SetDriverGroup( did, 1, SPAN_WSECT_DRIVER, ROOTC_WSECT_DRIVER, TIPC_WSECT_DRIVER );
    SetParmVal( did, "Span", "XSec_1", 1.5 );
    SetParmVal( did, "Root_Chord", "XSec_1", {dorsal_cr:.4f} );
    SetParmVal( did, "Tip_Chord", "XSec_1", 1.4 );
    SetParmVal( did, "Sweep", "XSec_1", 76.0 );
    SetParmVal( did, "Sweep_Location", "XSec_1", 0.0 );
    SetParmVal( did, "Dihedral", "XSec_1", 0.0 );
    SetParmVal( did, "Twist", "XSec_1", 0.0 );
    SetParmVal( did, "SectTess_U", "XSec_1", 6 );
    Update();
    SetParmVal( did, "ThickChord", "XSecCurve_0", 0.05 );
    SetParmVal( did, "ThickChord", "XSecCurve_1", 0.05 );
    Update();

    //================= Horizontal tail (RESIZED, on the fin tip) =============//
    string hid = AddGeom( "WING", "" );
    SetGeomName( hid, "HorizTail" );
    SetParmVal( hid, "X_Rel_Location", "XForm", {ht_x:.4f} );
    SetParmVal( hid, "Z_Rel_Location", "XForm", {ht_z:.4f} );
    SetDriverGroup( hid, 1, SPAN_WSECT_DRIVER, ROOTC_WSECT_DRIVER, TIPC_WSECT_DRIVER );
    SetParmVal( hid, "Span", "XSec_1", {ht_semib:.4f} );
    SetParmVal( hid, "Root_Chord", "XSec_1", {ht_cr:.4f} );
    SetParmVal( hid, "Tip_Chord", "XSec_1", {ht_ct:.4f} );
    SetParmVal( hid, "Sweep", "XSec_1", 20.0 );
    SetParmVal( hid, "Sweep_Location", "XSec_1", 0.25 );
    SetParmVal( hid, "Dihedral", "XSec_1", 0.0 );
    SetParmVal( hid, "Twist", "XSec_1", 0.0 );
    SetParmVal( hid, "SectTess_U", "XSec_1", 16 );
    Update();

    //================================= Sets ==================================//
    SetSetName( 3, "ThickBodies" );
    SetSetName( 4, "ThinLifting" );
    SetSetFlag( fid, 3, {in_fuselage} );
    SetSetFlag( bid, 3, {in_bellyfairing} );
    SetSetFlag( nid, 3, {in_nacelle} );
    SetSetFlag( wid, 4, {in_mainwing} );
    SetSetFlag( pid, 4, {in_pylon} );
    SetSetFlag( vid, 4, {in_verttail} );
    SetSetFlag( did, 4, {dorsal_in_set} );
    SetSetFlag( hid, 4, {in_horiztail} );
    Update();

    Print( "VT area (expect {s_vt:.2f}): " + GetParmVal( vid, "TotalArea", "WingGeom" ) );
    Print( "HT area (expect {s_ht:.2f}): " + GetParmVal( hid, "TotalArea", "WingGeom" ) );
    Print( "Wing area (expect 201.76 incl winglet): " + GetParmVal( wid, "TotalArea", "WingGeom" ) );
    WriteVSPFile( "{name}.vsp3", SET_ALL );

    //=============================== Analysis ================================//
    string cg = "VSPAEROComputeGeometry";
    SetAnalysisInputDefaults( cg );
    array<int> gset = {{ 3 }};  SetIntAnalysisInput( cg, "GeomSet", gset );
    array<int> tset = {{ 4 }};  SetIntAnalysisInput( cg, "ThinGeomSet", tset );
    ExecAnalysis( cg );

    string an = "VSPAEROSweep";
    SetAnalysisInputDefaults( an );
    SetIntAnalysisInput( an, "GeomSet", gset );
    SetIntAnalysisInput( an, "ThinGeomSet", tset );
    array<double> sref = {{ {sref} }};  SetDoubleAnalysisInput( an, "Sref", sref );
    array<double> bref = {{ {bref} }};  SetDoubleAnalysisInput( an, "bref", bref );
    array<double> cref = {{ {cref} }};  SetDoubleAnalysisInput( an, "cref", cref );
    array<double> xcg  = {{ {xcg:.4f} }};  SetDoubleAnalysisInput( an, "Xcg", xcg );
    array<double> zcg  = {{ -1.0 }};    SetDoubleAnalysisInput( an, "Zcg", zcg );
    array<double> a0   = {{ {a0} }};    SetDoubleAnalysisInput( an, "AlphaStart", a0 );
    array<double> a1   = {{ {a1} }};    SetDoubleAnalysisInput( an, "AlphaEnd", a1 );
    array<int>    na   = {{ {na} }};    SetIntAnalysisInput( an, "AlphaNpts", na );
    array<double> b0   = {{ {b0} }};    SetDoubleAnalysisInput( an, "BetaStart", b0 );
    array<double> b1   = {{ {b1} }};    SetDoubleAnalysisInput( an, "BetaEnd", b1 );
    array<int>    nb   = {{ {nb} }};    SetIntAnalysisInput( an, "BetaNpts", nb );
    array<double> m0   = {{ 0.30 }};    SetDoubleAnalysisInput( an, "MachStart", m0 );
    array<int>    nm   = {{ 1 }};       SetIntAnalysisInput( an, "MachNpts", nm );
    array<double> re   = {{ 8000000.0 }}; SetDoubleAnalysisInput( an, "ReCref", re );
    array<int>    ncpu = {{ 10 }};      SetIntAnalysisInput( an, "NCPU", ncpu );
    array<int>    wni  = {{ 5 }};       SetIntAnalysisInput( an, "WakeNumIter", wni );
    ExecAnalysis( an );
    Print( "DONE {name}" );

    while ( GetNumTotalErrors() > 0 )
    {{
        ErrorObj err = PopLastError();
        Print( err.GetErrorString() );
    }}
}}
'''


def fmt(vals):
    return ", ".join(f"{v:.5f}" for v in vals)


COMPONENTS = ["Fuselage", "BellyFairing", "MainWing", "Nacelle", "Pylon",
             "VertTail", "DorsalFin", "HorizTail"]


def make(name, s_ht, s_vt, x_wing, xcg, mode, dorsal=True, exclude=None):
    """Write a variant's build+run script into its own directory.

    exclude: component name (from COMPONENTS) to leave OUT of the analysis
    GeomSet/ThinGeomSet -- built but contributing zero force. Used for the
    leave-one-out pitching-moment buildup: baseline minus (baseline w/o
    component X) isolates X's net moment contribution, interference included.
    """
    ht, vt = st.tail_geometry(s_ht, s_vt)
    # The dorsal fin's root chord must still reach the (possibly moved) fin LE.
    # v5 ran apex x=26.5 to the fin root at 31.6 with cr=6.2; hold that overlap.
    # Diagnostic: the dorsal is a thin VLM surface whose fixed 6.2 ft root
    # overlaps the (resizable) fin root. Overlapping thin surfaces
    # interpenetrate in a VLM, so it can be switched off to test whether it
    # is corrupting Cn_beta.
    dorsal_cr = 6.2

    if mode == "alpha":
        a0, a1, na, b0, b1, nb = 0.0, 8.0, 5, 0.0, 0.0, 1
    elif mode == "point":
        a0, a1, na, b0, b1, nb = 3.7, 3.7, 1, 0.0, 0.0, 1
    else:
        a0, a1, na, b0, b1, nb = 3.7, 3.7, 1, 0.0, 6.0, 4

    dorsal_flag = dorsal and exclude != "DorsalFin"
    inflag = {c: ("false" if c == exclude else "true") for c in COMPONENTS}

    d = os.path.join(HERE, name)
    os.makedirs(d, exist_ok=True)
    body = TEMPLATE.format(
        name=name, s_ht=s_ht, s_vt=s_vt, x_wing=x_wing,
        in_fuselage=inflag["Fuselage"], in_bellyfairing=inflag["BellyFairing"],
        in_nacelle=inflag["Nacelle"], in_mainwing=inflag["MainWing"],
        in_pylon=inflag["Pylon"], in_verttail=inflag["VertTail"],
        in_horiztail=inflag["HorizTail"],
        wing_dx=x_wing - 19.0, fuse_l=FUSE_L, nx=len(FUSE),
        fx=fmt([f[0] for f in FUSE]), fz=fmt([f[1] for f in FUSE]),
        fh=fmt([f[2] for f in FUSE]), fw=fmt([f[3] for f in FUSE]),
        fta=fmt([f[4] for f in FUSE]), fba=fmt([f[5] for f in FUSE]),
        fsa=fmt([f[6] for f in FUSE]), fst=fmt([f[7] for f in FUSE]),
        airfoil=AIRFOIL,
        x_vt=st.X_VT_ROOT, vt_b=vt["b"], vt_cr=vt["cr"], vt_ct=vt["ct"],
        dorsal_cr=dorsal_cr,
        ht_x=ht["x_root_le"], ht_z=ht["z"], ht_semib=ht["b"] / 2.0,
        ht_cr=ht["cr"], ht_ct=ht["ct"],
        dorsal_in_set="true" if dorsal_flag else "false",
        sref=SREF, bref=BREF, cref=CREF, xcg=xcg,
        a0=a0, a1=a1, na=na, b0=b0, b1=b1, nb=nb)
    with open(os.path.join(d, "build_run.vspscript"), "w") as fh:
        fh.write(body)
    return d


def run(d):
    r = subprocess.run([VSPSCRIPT, "-script", "build_run.vspscript"], cwd=d,
                       capture_output=True, text=True, timeout=3600)
    out = r.stdout.splitlines()
    keep = [l for l in out if any(k in l for k in
                                  ("area", "DONE", "rror", "Error", "ERROR"))]
    print(f"  {os.path.basename(d):22s} " + " | ".join(keep[-4:]))
    return r.returncode


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--baseline", action="store_true")
    ap.add_argument("--ht-sweep", action="store_true")
    ap.add_argument("--vt-sweep", action="store_true")
    ap.add_argument("--final", nargs=3, type=float, metavar=("S_HT", "S_VT", "XW"))
    ap.add_argument("--xcg", type=float, default=19.90)
    a = ap.parse_args()

    if a.baseline:
        print("baseline (v5 areas, v6 fuselage):")
        run(make("00_baseline", 51.68, 59.00, 15.9, a.xcg, "alpha"))

    if a.ht_sweep:
        print("S_HT parametric (S_VT, wing, Xcg all fixed):")
        for s in (30.0, 38.0, 46.0, 54.0, 62.42):
            run(make(f"ht{s:04.1f}", s, 59.00, 15.9, a.xcg, "alpha"))

    if a.vt_sweep:
        print("S_VT parametric (beta sweeps):")
        for s in (38.0, 44.0, 51.0, 59.0):
            run(make(f"vt{s:04.1f}_beta", 51.68, s, 15.9, a.xcg, "beta"))

    if a.final:
        s_ht, s_vt, xw = a.final
        print(f"final v6: S_HT={s_ht}, S_VT={s_vt}, wing LE={xw}")
        run(make("final_alpha", s_ht, s_vt, xw, a.xcg, "alpha"))
        run(make("final_beta", s_ht, s_vt, xw, a.xcg, "beta"))


if __name__ == "__main__":
    main()
